Setup Project
oursky/gitlab-cicd-dashboard pull request #5
Opened 2021-07-22 07:48 UTC by CMDRyan

Initiate required files 

- gitlabAPI.js : Defined to fetch Projects and Jobs using API provided by gitlab.
- gitJobs.js : Get and filter required data from gitlab using provided group ID.
- app.js: Localhost server on port: 8081.
Additionally, empty ejs template engine views are added.

Usage:

- $export API_TOKEN=`your token`
- $node app.js

- Browser: http://localhost:8081/groups/ `group ID` /jobs

2021-07-22 09:28 UTC, Steven-Chan requested changes
1. Please remove blackbox related thing in this commit
2. Do not check in tailwind.css here, it is a generated file.
3. Put source code files in `src` folder instead of the top level. Otherwise you will mix build phase code and runtime code together.

Put the steps to setup this project in README instead of PR comment.

2021-07-22 09:28 UTC, Steven-Chan commented on getJobs.js
> +    const gitlabAPI = require("./gitlabAPI");
Use require at top level in this file.

2021-07-22 09:28 UTC, Steven-Chan commented on getJobs.js
> +    const apiToken = process.env.API_TOKEN;
Constants should also be put in top level, or you can create a new file to put all server config called `config.js` and put all env var in it.

2021-07-22 09:28 UTC, Steven-Chan commented on getJobs.js
> +  return new Promise((resolve) => {
You don't need to create a new promise in this way. We only `new Promise` when transforming non-promise functions to promise.

2021-07-22 09:28 UTC, Steven-Chan commented on getJobs.js
> +        return ids;
Try using `map` of array to simplify the code.

2021-07-22 09:28 UTC, Steven-Chan commented on getJobs.js
> +        return Promise.all(data);
Try `map`.

2021-07-22 09:28 UTC, Steven-Chan commented on getJobs.js
> +        }
Try `filter`.

2021-07-22 09:28 UTC, Steven-Chan commented on gitlabAPI.js
> +  GroupID,
Do not use capital letter to start a param variable name.

2021-07-22 09:28 UTC, Steven-Chan commented on gitlabAPI.js
> +exports.getJobsByProjectID = function getJobsByProjectID(ProjectID, key) {
Do not use capital letter to start a param variable name.

2021-07-22 09:28 UTC, Steven-Chan commented on gitlabAPI.js
> +  searchParam
Please organize the function in better way. JS function param is unnamed, so the ordering is important. We group similar things together, so `key` should not be in the middle of `groupID` and `searchParams`.

2021-07-22 09:28 UTC, Steven-Chan commented on package.json
> +    "prettier": "2.3.2"
Please pin all to exact version and run `yarn` again.

2021-07-22 09:28 UTC, Steven-Chan commented on views/partials/head.ejs
> +<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.min.css">
We use tailwind instead of bootstrap, so please remove this.

2021-07-22 09:28 UTC, Steven-Chan commented on views/src/styles.css
> +@import url("https://fonts.googleapis.com/css2?family=Quicksand&display=swap");
This PR does not have UI yet, so please remove this file.

On the other hand, it looks to me that defining style here defeat the purpose of using tailwind.

2021-07-22 09:30 UTC, Steven-Chan commented
testing

2021-07-23 03:31 UTC, Steven-Chan commented on package.json
> +    "prettier": "2.3.2"
Not addressed

2021-07-23 03:39 UTC, Steven-Chan commented
@CMDRyan 

- blackbox not removed yet
- The tailwind.css is needed, but not committed and no instruction about it
- Dont say discussed minor issue in commit, list out what u have changed
- It is impossible to have both package-lock.json and yarn-lock.json at the same time

2021-07-23 07:02 UTC, CMDRyan commented
@Steven-Chan 

- Resent commit message
- Removed 'blackbox' related lines
- Removed package.json
- Added tailwind.css
-

2021-07-23 09:49 UTC, CMDRyan commented
@Steven-Chan 

Updated README with line: $yarn add express .

2021-07-23 11:33 UTC, CMDRyan commented
@Steven-Chan

- Updated README `yarn add express` to `yarn`
- Relocated all source code files to /src and corrected path in app.js
- getJobs.js will now return an array of Job objects

2021-07-26 02:49 UTC, merged