Implement grouping functionality
oursky/gitlab-cicd-dashboard pull request #56
Opened 2021-09-02 10:34 UTC by CMDRyan

@Steven-Chan 

UI changes
- Profile icon has been replaced with hamburger icon
- Hamburger icon will trigger curtain menu which includes groupby dropdown box

Added features
- Library can now handle groupBy function call and will return data to client in an array format
- GroupBy function has been added
   - By machine type
   - By Project name

To-Do:
- Align number designs

2021-09-03 03:09 UTC, Steven-Chan requested changes

2021-09-03 03:09 UTC, Steven-Chan commented on src/getData.js
> +        projectList.push(Project);
Bad code style. Missing "const". Variable name should be camelcase starts with small letters.

2021-09-03 03:09 UTC, Steven-Chan commented on src/getData.js
> +        projectList.push(Project);
I just found this style also appears somewhere else, pls help fix them altogether.

2021-09-03 10:02 UTC, CMDRyan commented
@Steven-Chan 

- Added const to object decorations
- Refactored groupBy "none", following the same style as other criteria
- Refactored group titles html building method using `Template` element
- Modified title css to compatible with the `Template` element

2021-09-05 14:06 UTC, CMDRyan commented
@Steven-Chan

Changes to UI:

- Changed feedback for cards to colour changing (white to light gray)
- Removed curtain navigation menu

<img width="1440" alt="Screenshot 2021-09-05 at 9 59 23 PM" src="https://user-images.githubusercontent.com/85364009/132129812-a8961ddb-0abe-4af5-bda2-040498430b6c.png">

<img width="378" alt="Screenshot 2021-09-05 at 10 01 01 PM" src="https://user-images.githubusercontent.com/85364009/132129822-e9c056f5-1021-4d57-8f35-e34f35377c4e.png">

2021-09-07 07:10 UTC, Steven-Chan requested changes

2021-09-07 07:10 UTC, Steven-Chan commented on src/views/partials/jobCard.ejs
> +      <div class="flex flex-grow-0">Project:</div>
Also you only specify the flex-grow, but not flex-shrink. Most cases I think we don't specify flex-grow or flex-shrink separately but use flex-1 directly. If the element has a fixed size, i think you better want to give it a fix width instead.

2021-09-07 07:10 UTC, Steven-Chan commented on src/views/partials/singleJobCard.ejs
> +  <a href="<%=job.web_url%>" target="_blank">
I just realize there is a `jobCard.js` and `singleJobCard.js`. Can you help refactor and make them one single template file.

2021-09-07 07:10 UTC, Steven-Chan commented on src/views/pages/index.ejs
> +  </template>
What is this?

2021-09-07 07:10 UTC, Steven-Chan commented on src/views/pages/index.ejs
> +        titleDiv[3].innerHTML = groupJobs.length
Don't use index to access the element.

2021-09-07 07:11 UTC, Steven-Chan commented
@CMDRyan  Pls also include screenshot with card.

2021-09-08 03:50 UTC, CMDRyan commented
Full screen: (hovering on one card):
<img width="1335" alt="Screenshot 2021-09-08 at 11 48 16 AM" src="https://user-images.githubusercontent.com/85364009/132443508-a25a0abf-c3f7-4fed-88ef-75c105aa1a07.png">

Mobile size (grouped by):
<img width="499" alt="Screenshot 2021-09-08 at 11 48 59 AM" src="https://user-images.githubusercontent.com/85364009/132443550-234fbfc8-b066-47cc-a42d-0b907c4ebad2.png">

2021-09-08 04:23 UTC, Steven-Chan requested changes
@CMDRyan 
- The section header hight needs larger, it is too tight now
- The job count in section header is not aligned
- The job card spacing looks different in narrow screen and wide screen

2021-09-09 01:51 UTC, CMDRyan commented
@Steven-Chan 

- The cards rendering are refactored, and the extra jobCards.js is removed
- The header section padding has been increased
- Job card spacing in mobile view has been fixed
- Template function no longer uses index method to change element

2021-09-09 03:34 UTC, CMDRyan commented
Margin fixed for mobile view: 

<img width="572" alt="Screenshot 2021-09-09 at 11 33 21 AM" src="https://user-images.githubusercontent.com/85364009/132618124-f2b58134-4759-4c2d-a76d-e4263d9f8511.png">

2021-09-09 05:04 UTC, CMDRyan commented
Grouping header paddings and number fix:
<img width="394" alt="Screenshot 2021-09-09 at 1 03 18 PM" src="https://user-images.githubusercontent.com/85364009/132625852-2050be47-04f1-4383-bfbd-d5031ac86012.png">

2021-09-09 09:48 UTC, Steven-Chan requested changes

2021-09-09 09:48 UTC, Steven-Chan commented on src/app.js
> +      runningCards.push(jobObj)
This is not the correct way to use map. You transform the value of an array with map and the output of map is the array of new value already.

2021-09-09 09:48 UTC, Steven-Chan commented on src/app.js
> +      );
The template does not change in every request, so we should load it globally once.

2021-09-10 03:05 UTC, CMDRyan commented
@Steven-Chan 
- Card template has been made global
- Corrected logic of array mappings

2021-09-10 04:00 UTC, merged